- name: CVMFS
  hosts: cvmfsstratum0servers
  become: true
  vars:
    cvmfs_numfiles: 4096
    cvmfs_srv_device: /dev/vdc
    cvmfs_server_urls:
      - domain: cloud.ba.infn.it
        urls:
          - "http://cloud-90-147-102-226.cloud.ba.infn.it/cvmfs/@fqrn@"
    cvmfs_repositories:
      - repository: tools.elixir-italy-cvmfs
        stratum0: cloud-90-147-102-226.cloud.ba.infn.it
        key_dir: /etc/cvmfs/keys/tools.elixir-italy-cvmfs.key
        server_options:
          - CVMFS_AUTO_TAG=false
          - CVMFS_GARBAGE_COLLECTION=true
          - CVMFS_AUTO_GC=false
        client_options:
          - CVMFS_NFILES=4096
  pre_tasks:
    - name: format buffer volume
      filesystem:
        fstype: ext4
        dev: /dev/vdb

    - name: create mount point
      file:
        state: directory
        path: /buffer

    - name: mount buffer
      mount:
        path: /buffer
        src: /dev/vdb
        fstype: ext4
        opts: rw
        state: present
  roles:
    - galaxyproject.cvmfs

#before install cvmfs client following instruction at https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#debian-ubuntu
